name = "zephyr-phoenix"


#Pairs table

[[tables]]
name = "pho_pairs"

[[tables.columns]]
name = "address"
col_type = "BYTEA"

[[tables.columns]]
name = "token_a"
col_type = "BYTEA"

[[tables.columns]]
name = "token_b"
col_type = "BYTEA"

[[tables.columns]]
name = "reserve_a"
col_type = "BYTEA"

[[tables.columns]]
name = "reserve_b"
col_type = "BYTEA"

[[tables.columns]]
name = "fee"
col_type = "BYTEA"
