name = "zephyr-comet"


#Comet Pairs table

[[tables]]
name = "comet"

[[tables.columns]]
name = "address"
col_type = "BYTEA"

[[tables.columns]]
name = "token_a"
col_type = "BYTEA"

[[tables.columns]]
name = "token_b"
col_type = "BYTEA"

[[tables.columns]]
name = "reserve_a"
col_type = "BYTEA"

[[tables.columns]]
name = "reserve_b"
col_type = "BYTEA"