name = "zephyr-soroswap"

#Soroswap Router events table

[[tables]]
name = "ssw_rt_ev"

[[tables.columns]]
name = "e_type"
col_type = "BYTEA"

[[tables.columns]]
name = "token_a"
col_type = "BYTEA"

[[tables.columns]]
name = "token_b"
col_type = "BYTEA"

[[tables.columns]]
name = "amount_a"
col_type = "BYTEA"

[[tables.columns]]
name = "amount_b"
col_type = "BYTEA"

[[tables.columns]]
name = "account"
col_type = "BYTEA"

[[tables.columns]]
name = "timestamp"
col_type = "BYTEA"

[[tables.columns]]
name = "tx_hash"
col_type = "BYTEA"


#Soroswap Pairs table

[[tables]]
name = "ssw_pairs"

[[tables.columns]]
name = "address"
col_type = "BYTEA"

[[tables.columns]]
name = "token_a"
col_type = "BYTEA"

[[tables.columns]]
name = "token_b"
col_type = "BYTEA"

[[tables.columns]]
name = "reserve_a"
col_type = "BYTEA"

[[tables.columns]]
name = "reserve_b"
col_type = "BYTEA"

#Soroswap Reserves changes table

[[tables]]
name = "ssw_rs_ch"

[[tables.columns]]
name = "address"
col_type = "BYTEA"

[[tables.columns]]
name = "reserve_a"
col_type = "BYTEA"

[[tables.columns]]
name = "reserve_b"
col_type = "BYTEA"

[[tables.columns]]
name = "timestamp"
col_type = "BYTEA"


#Soroswap Providers table

[[tables]]
name = "ssw_prov"

[[tables.columns]]
name = "provider_address"
col_type = "BYTEA"

[[tables.columns]]
name = "pool_address"
col_type = "BYTEA"

[[tables.columns]]
name = "shares"
col_type = "BYTEA"

[[tables.columns]]
name = "percentage"
col_type = "BYTEA"


